version: '3.8'

services:
  fastapi_service:
    build: ./fastapi
    ports:
      - "8000:8000"
  
  streamlit_service:
    build: ./streamlit
    ports:
      - "8501:8501"
    environment:
      - BASE_URL=http://fastapi_service:8000
